version: "3.5"

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGERS_USER: postgres
      POSTGERS_PASSWORD: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
    PGADMIN_DEFAULT_EMAIL: postgres@email.ru
    PGADMIN_DEFAULT_PASSWORD: postgres
    PGADMIN_CONFIG_SERVER_MODE: "False"
